const todayKey=()=>new Date().toISOString().slice(0,10);
const dateID=()=>new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());
const seedUsers=[
 {id:'G001',password:'123456',name:'Pak Komarudin',role:'guru'},
 {id:'G002',password:'123456',name:'Ibu Rina',role:'guru'},
 {id:'ADMIN',password:'admin123',name:'Administrator',role:'admin'}
];
const classes=['7A','7B','7C','7D','7E','7F','7G','7H','7I','8A','8B','8C','8D','8E','8F','8G','8H','8I','9A','9B','9C','9D','9E','9F','9G','9H','9I'];
function studentSeed(){let out=[];classes.forEach((c,ci)=>{for(let i=1;i<=12;i++) out.push({nis:`${c.replace(/\D/g,'')}${String(ci+1).padStart(2,'0')}${String(i).padStart(2,'0')}`,name:`Siswa ${c}-${String(i).padStart(2,'0')}`,class:c})});return out}
const db={
 get users(){return JSON.parse(localStorage.getItem('eco_users')||'null')||seedUsers},
 set users(v){localStorage.setItem('eco_users',JSON.stringify(v))},
 get students(){return JSON.parse(localStorage.getItem('eco_students')||'null')||studentSeed()},
 set students(v){localStorage.setItem('eco_students',JSON.stringify(v))},
 get records(){return JSON.parse(localStorage.getItem('eco_records')||'[]')},
 set records(v){localStorage.setItem('eco_records',JSON.stringify(v))}
};
if(!localStorage.getItem('eco_users')) db.users=seedUsers;if(!localStorage.getItem('eco_students')) db.students=studentSeed();
let state={user:null,page:'home',selectedClass:null};
const $=s=>document.querySelector(s);const content=$('#content');
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function setSession(u){state.user=u;localStorage.setItem('eco_session',u?JSON.stringify({id:u.id}):'');renderShell()}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#loginId').value.trim().toUpperCase(),pw=$('#loginPassword').value;const u=db.users.find(x=>x.id.toUpperCase()===id&&x.password===pw);if(!u)return toast('ID atau password salah');setSession(u)});
$('#logoutBtn').onclick=()=>{localStorage.removeItem('eco_session');state.user=null;renderShell()};
$('#menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
function navItems(){const base=[['home','🏠 Beranda'],['input','📝 Pendataan'],['recap','📊 Rekap'],['account','👤 Akun']];if(state.user?.role==='admin')base.splice(3,0,['master','⚙️ Kelola Data']);return base}
function renderShell(){if(!state.user){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');return}$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userChip').innerHTML=`<b>${state.user.name}</b><br>${state.user.role==='admin'?'Admin':'Guru'}`;$('#nav').innerHTML=navItems().map(([k,l])=>`<button class="nav-btn ${state.page===k?'active':''}" data-page="${k}">${l}</button>`).join('');document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.selectedClass=null;renderShell();document.querySelector('.sidebar').classList.remove('open')});renderPage()}
function recordsToday(){return db.records.filter(r=>r.date===todayKey())}
function classRecord(c){return recordsToday().find(r=>r.class===c)}
function pageMeta(title,sub=''){ $('#pageTitle').textContent=title;$('#pageSubtitle').textContent=sub }
function renderPage(){if(state.page==='home')return home();if(state.page==='input')return inputPage();if(state.page==='recap')return recap();if(state.page==='account')return account();if(state.page==='master')return master()}
function home(){pageMeta('Beranda',dateID());const rt=recordsToday();const done=new Set(rt.map(r=>r.class));const items=rt.flatMap(r=>r.items.filter(i=>i.presence==='hadir'));const food=items.length?Math.round(items.filter(i=>i.food).length/items.length*100):0;const tumb=items.length?Math.round(items.filter(i=>i.tumbler).length/items.length*100):0;content.innerHTML=`
<div class="grid stats"><div class="stat"><span>Kelas selesai</span><strong>${done.size}/${classes.length}</strong></div><div class="stat"><span>Belum didata</span><strong>${classes.length-done.size}</strong></div><div class="stat"><span>Membawa wadah</span><strong>${food}%</strong></div><div class="stat"><span>Membawa tumbler</span><strong>${tumb}%</strong></div></div>
<div class="grid two-col" style="margin-top:16px"><div class="card"><div class="section-head"><h3>Status Pendataan Hari Ini</h3><button class="btn primary" onclick="goInput()">Mulai Pendataan</button></div><div class="grid class-grid">${classes.map(c=>{const r=classRecord(c);return `<button class="class-btn ${r?'done':'pending'}" onclick="openClass('${c}')"><b>${c}</b><small>${r?'✓ '+r.inputByName:'Belum didata'}</small></button>`}).join('')}</div></div><div class="card"><h3>Ringkasan</h3><p>Guru dapat mendata kelas mana pun. Kelas yang sudah disimpan tetap dapat dilihat, sedangkan koreksi akan tercatat.</p><div class="notice">Fokus hari ini: selesaikan ${classes.length-done.size} kelas yang belum didata.</div></div></div>`}
window.goInput=()=>{state.page='input';renderShell()};window.openClass=c=>{state.page='input';state.selectedClass=c;renderShell()};
function inputPage(){pageMeta('Pendataan','Pilih kelas lalu tandai kondisi siswa');if(!state.selectedClass){content.innerHTML=`<div class="card"><h3>Pilih Kelas</h3><div class="grid class-grid">${classes.map(c=>{const r=classRecord(c);return `<button class="class-btn ${r?'done':'pending'}" onclick="openClass('${c}')"><b>${c}</b><small>${r?'Sudah didata':'Belum didata'}</small></button>`}).join('')}</div></div>`;return}renderClassForm(state.selectedClass)}
function renderClassForm(c){const students=db.students.filter(s=>s.class===c);const existing=classRecord(c);let items=existing?JSON.parse(JSON.stringify(existing.items)):students.map(s=>({nis:s.nis,name:s.name,presence:'hadir',food:true,tumbler:true}));window.formItems=items;const locked=existing&&existing.inputBy!==state.user.id&&state.user.role!=='admin';content.innerHTML=`<div class="section-head"><div><h3 style="margin:0">Kelas ${c}</h3><small>${existing?`Sudah didata oleh ${existing.inputByName} • ${existing.time}`:'Belum pernah disimpan hari ini'}</small></div><button class="btn ghost" onclick="backClasses()">← Pilih kelas lain</button></div>${locked?'<div class="notice">Data dibuat guru lain. Anda dapat melihatnya. Tekan “Koreksi Data” untuk membuka perubahan; koreksi akan dicatat.</div>':''}<div class="card"><div class="toolbar"><button class="btn secondary" onclick="setAll('presence','hadir')">Semua Hadir</button><button class="btn secondary" onclick="setAll('food',true)">Semua Bawa Wadah</button><button class="btn secondary" onclick="setAll('tumbler',true)">Semua Bawa Tumbler</button>${locked?'<button id="unlockBtn" class="btn ghost" onclick="unlockCorrection()">Koreksi Data</button>':''}</div><div class="table-wrap"><table><thead><tr><th>No</th><th>NIS</th><th>Nama Siswa</th><th>Kehadiran</th><th>Wadah</th><th>Tumbler</th></tr></thead><tbody id="studentRows"></tbody></table></div><div style="display:flex;justify-content:flex-end;margin-top:16px"><button id="saveBtn" class="btn primary" ${locked?'disabled':''} onclick="saveClass('${c}')">Simpan Data ${c}</button></div></div>`;window.formLocked=!!locked;renderStudentRows()}
window.backClasses=()=>{state.selectedClass=null;renderPage()};
window.unlockCorrection=()=>{window.formLocked=false;$('#saveBtn').disabled=false;$('#unlockBtn').disabled=true;renderStudentRows();toast('Mode koreksi aktif')};
window.setAll=(field,val)=>{if(window.formLocked)return;window.formItems.forEach(i=>{if(field==='presence')i.presence=val;else if(i.presence==='hadir')i[field]=val});renderStudentRows()};
function renderStudentRows(){const rows=$('#studentRows');if(!rows)return;rows.innerHTML=window.formItems.map((i,idx)=>`<tr><td>${idx+1}</td><td>${i.nis}</td><td><b>${i.name}</b></td><td><select ${window.formLocked?'disabled':''} onchange="changePresence(${idx},this.value)"><option value="hadir" ${i.presence==='hadir'?'selected':''}>Hadir</option><option value="izin" ${i.presence==='izin'?'selected':''}>Izin</option><option value="sakit" ${i.presence==='sakit'?'selected':''}>Sakit</option><option value="alpa" ${i.presence==='alpa'?'selected':''}>Alpa</option></select></td><td><div class="switch ${i.food&&i.presence==='hadir'?'on':''}" onclick="toggleItem(${idx},'food')"></div></td><td><div class="switch ${i.tumbler&&i.presence==='hadir'?'on':''}" onclick="toggleItem(${idx},'tumbler')"></div></td></tr>`).join('')}
window.changePresence=(idx,v)=>{if(window.formLocked)return;const i=window.formItems[idx];i.presence=v;if(v!=='hadir'){i.food=false;i.tumbler=false}renderStudentRows()};window.toggleItem=(idx,f)=>{if(window.formLocked)return;const i=window.formItems[idx];if(i.presence!=='hadir')return;i[f]=!i[f];renderStudentRows()};
window.saveClass=c=>{const all=db.records;const oldIndex=all.findIndex(r=>r.date===todayKey()&&r.class===c);const now=new Date();const old=oldIndex>=0?all[oldIndex]:null;const rec={date:todayKey(),class:c,items:window.formItems,inputBy:state.user.id,inputByName:state.user.name,time:now.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),history:old?[...(old.history||[]),{editedAt:now.toISOString(),previousInputBy:old.inputByName,editedBy:state.user.name}]:[]};if(oldIndex>=0)all[oldIndex]=rec;else all.push(rec);db.records=all;toast(`Data ${c} berhasil disimpan`);state.selectedClass=null;renderPage()};
function recap(){pageMeta('Rekap','Ringkasan kepatuhan wadah dan tumbler');const recs=recordsToday();const cards=classes.map(c=>{const r=recs.find(x=>x.class===c);if(!r)return {c,food:0,tumb:0,both:0,status:'Belum'};const hadir=r.items.filter(i=>i.presence==='hadir');const pct=f=>hadir.length?Math.round(hadir.filter(f).length/hadir.length*100):0;return {c,food:pct(i=>i.food),tumb:pct(i=>i.tumbler),both:pct(i=>i.food&&i.tumbler),status:'Selesai'}});content.innerHTML=`<div class="card"><div class="section-head"><h3>Rekap Hari Ini</h3><span class="badge neutral">${dateID()}</span></div><div class="table-wrap"><table><thead><tr><th>Kelas</th><th>Status</th><th>Wadah</th><th>Tumbler</th><th>Keduanya</th></tr></thead><tbody>${cards.map(x=>`<tr><td><b>${x.c}</b></td><td><span class="badge ${x.status==='Selesai'?'ok':'warn'}">${x.status}</span></td><td>${x.food}%</td><td>${x.tumb}%</td><td><div style="display:flex;align-items:center;gap:8px"><div class="progress" style="width:120px"><i style="width:${x.both}%"></i></div><b>${x.both}%</b></div></td></tr>`).join('')}</tbody></table></div></div>`}
function account(){pageMeta('Akun','Informasi pengguna');content.innerHTML=`<div class="card" style="max-width:600px"><h3>${state.user.name}</h3><p><b>ID:</b> ${state.user.id}</p><p><b>Peran:</b> ${state.user.role==='admin'?'Administrator':'Guru'}</p><div class="notice">Akun guru dapat input, melihat rekap, dan melakukan koreksi terbatas. Pengelolaan siswa, kelas, guru, serta pengaturan sistem hanya untuk admin.</div></div>`}
function master(){if(state.user.role!=='admin'){state.page='home';return renderShell()}pageMeta('Kelola Data','Khusus Administrator');content.innerHTML=`<div class="grid two-col"><div class="card"><h3>Master Siswa</h3><p>${db.students.length} siswa • ${classes.length} kelas</p><div class="notice">Versi awal menggunakan data demo. Struktur sudah disiapkan untuk import Excel dan Firebase pada tahap berikutnya.</div></div><div class="card"><h3>Akun Guru</h3>${db.users.filter(u=>u.role==='guru').map(u=>`<p><b>${u.name}</b><br><small>${u.id}</small></p>`).join('')}</div></div>`}
(function boot(){const sess=localStorage.getItem('eco_session');if(sess){try{const id=JSON.parse(sess).id;state.user=db.users.find(u=>u.id===id)||null}catch{}}renderShell()})();
