const app=firebase.apps.length?firebase.app():firebase.initializeApp(window.PAKKOM_FIREBASE_CONFIG);
const auth=firebase.auth(),db=firebase.firestore();
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=v=>String(v||'').toUpperCase().replace(/KELAS/g,'').replace(/\s+/g,'').trim();
let user=null,profile=null,tasks=[],subs=[],groups=[],programs=[],activeFilter='all',assessmentCuts=[69,79,89];
function ranges(){const [a,b,c]=assessmentCuts;return[{min:0,max:a,label:'Perlu Bimbingan'},{min:a+1,max:b,label:'Berkembang'},{min:b+1,max:c,label:'Cakap'},{min:c+1,max:100,label:'Mahir'}]}
function scoreCategory(score){const n=Number(score);if(!Number.isFinite(n)||n<0||n>100)return '';return ranges().find(r=>n>=r.min&&n<=r.max)?.label||''}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function close(){ $('#modal').classList.add('hidden'); $('#modalBody').innerHTML=''; }
$('#closeModal').onclick=close;$('#logout').onclick=async()=>{try{await db.collection('users').doc(user.uid).delete()}catch(_){}await auth.signOut();location.href='../'};
function groupForTask(taskId){return groups.find(g=>g.taskId===taskId)}
function subForTask(t){if(t.taskType==='group'){const g=groupForTask(t.id);return g?subs.find(s=>s.groupKey===g.groupKey):null}return subs.find(s=>s.taskId===t.id&&String(s.nis)===String(profile.loginId))}
function statusOf(t){const s=subForTask(t);if(!s)return 'todo';if(s.status==='revision')return 'revision';if(s.status==='graded')return 'graded';if(s.status==='submitted')return 'submitted';return 'draft'}
function statusLabel(k){return ({todo:'Belum Dikerjakan',draft:'Draf',submitted:'Sudah Dikumpulkan',revision:'Perlu Perbaikan',graded:'Sudah Dinilai'})[k]||k}
function dueText(t){return t.dueDate||'Tanpa batas'}
async function loadAssessment(){try{const d=await db.collection('settings').doc('taskAssessment').get();if(d.exists&&Array.isArray(d.data().cutoffs)){const c=d.data().cutoffs.map(Number);if(c.length===3&&c[0]>=0&&c[0]<c[1]&&c[1]<c[2]&&c[2]<100)assessmentCuts=c}}catch(_){}}
async function load(){await loadAssessment();const classId=norm(profile.classId);try{const ps=await db.collection('cocurricularPrograms').where('active','==',true).get();programs=ps.docs.map(d=>({id:d.id,...d.data()}))}catch(_){programs=[]}const a=await db.collection('assignments').where('targetClasses','array-contains',classId).get();tasks=a.docs.map(d=>({id:d.id,...d.data()})).filter(t=>t.published===true&&t.archived!==true);const nis=String(profile.loginId);const own=await db.collection('taskSubmissions').where('nis','==',nis).get();const member=await db.collection('taskSubmissions').where('memberNis','array-contains',nis).get();const map=new Map();[...own.docs,...member.docs].forEach(d=>map.set(d.id,{id:d.id,...d.data()}));subs=[...map.values()];const gs=await db.collection('taskGroups').where('memberNis','array-contains',nis).get();groups=gs.docs.map(d=>({id:d.id,...d.data()}));draw()}
function draw(){const counts={todo:0,draft:0,revision:0,submitted:0,graded:0};tasks.forEach(t=>counts[statusOf(t)]++);$('#summary').innerHTML=`<button data-f="todo"><b>${counts.todo}</b><span>Belum</span></button><button data-f="revision"><b>${counts.revision}</b><span>Perbaikan</span></button><button data-f="submitted"><b>${counts.submitted}</b><span>Dikumpulkan</span></button><button data-f="graded"><b>${counts.graded}</b><span>Dinilai</span></button>`;const list=tasks.filter(t=>activeFilter==='all'||statusOf(t)===activeFilter);$('#filterRow').innerHTML=`<button class="chip ${activeFilter==='all'?'active':''}" data-f="all">Semua</button>${['todo','draft','revision','submitted','graded'].map(k=>`<button class="chip ${activeFilter===k?'active':''}" data-f="${k}">${statusLabel(k)}</button>`).join('')}`;document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.f;draw()});$('#view').innerHTML=list.length?`<div class="grid">${list.map(t=>{const s=subForTask(t),st=statusOf(t),g=groupForTask(t.id);const p=programs.find(x=>x.id===t.programId);return `<article class="card task">${p?`<div class="notice"><b>${esc(p.name||'Kokurikuler')}</b><br><small>Tema: ${esc(p.theme||'-')}<br>Topik: ${esc(p.topic||'-')}</small></div>`:''}<div class="tags"><span class="tag">${t.taskType==='group'?'Kelompok':'Individu'}</span><span class="tag status-${st}">${statusLabel(st)}</span></div><h3>${esc(t.title)}</h3>${t.taskType==='group'&&g?`<div class="notice"><b>Kelompok ${esc(g.groupNo)}</b><br><small>${esc((g.memberNames||[]).join(', '))}</small></div>`:''}<p>${esc(t.description||'')}</p><div class="meta">Batas: ${esc(dueText(t))}</div>${s?.feedback?`<div class="notice"><b>Catatan guru:</b> ${esc(s.feedback)}</div>`:''}${st==='graded'?`<div class="meta"><b>Nilai ${esc(s.score??'-')} • ${esc(scoreCategory(s.score)||'-')}</b></div>`:''}<button class="primary" data-open="${t.id}">${st==='graded'?'Lihat Nilai':st==='submitted'?'Lihat Pengumpulan':st==='revision'?'Perbaiki Tugas':'Kerjakan'}</button></article>`}).join('')}</div>`:'<div class="card empty">Tidak ada tugas pada kategori ini.</div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openTask(b.dataset.open))}
function taskComponents(t){if(Array.isArray(t.components)&&t.components.length)return t.components;return[{type:t.answerType||'link',label:'Jawaban',required:true,count:1,requireDescription:(t.answerType||'link')==='link'}]}
function answerKey(ci,ii){return `${ci}_${ii}`}
function openTask(id){const t=tasks.find(x=>x.id===id),s=subForTask(t),g=t.taskType==='group'?groupForTask(t.id):null;if(t.taskType==='group'&&!g)return modal('<h2>Tugas Kelompok</h2><div class="notice">Keanggotaan kelompok Anda belum tersedia. Hubungi Admin/Wali Kelas.</div>');const st=statusOf(t),locked=st==='graded'||st==='submitted',components=taskComponents(t),oldAnswers=Array.isArray(s?.answers)?s.answers:[];const fields=components.map((c,ci)=>Array.from({length:Math.max(1,Number(c.count)||1)},(_,ii)=>{const old=oldAnswers.find(a=>Number(a.componentIndex)===ci&&Number(a.itemIndex)===ii)||{},key=answerKey(ci,ii),label=`${c.label||'Jawaban'}${Number(c.count)>1?' '+(ii+1):''}`;if(c.type==='text')return `<div class="field"><label>${esc(label)} ${c.required?'*':''}</label><textarea data-answer="${key}" ${locked?'disabled':''}>${esc(old.text||'')}</textarea></div>`;return `<div class="field"><label>${esc(label)} ${c.required?'*':''}</label><input data-answer="${key}" type="url" placeholder="https://..." value="${esc(old.url||'')}" ${locked?'disabled':''}><small>${c.type==='photo'?'Link foto':c.type==='video'?'Link video':c.type==='document'?'Link dokumen':'Link'}</small><textarea data-description="${key}" placeholder="Keterangan ${c.requireDescription?'(wajib)':''}" ${locked?'disabled':''}>${esc(old.description||'')}</textarea></div>`}).join('')).join('');modal(`<h2>${esc(t.title)}</h2>${g?`<div class="notice"><b>Kelompok ${esc(g.groupNo)}</b><br>${esc((g.memberNames||[]).join(', '))}<br><small>Cukup satu anggota mengumpulkan. Semua anggota kelompok akan melihat status yang sama.</small></div>`:''}<p>${esc(t.description||'')}</p><div class="meta">Batas: ${esc(dueText(t))}</div>${fields}<div class="notice"><small>Foto, video, dan dokumen dikumpulkan melalui link. Jika menggunakan Google Drive, pastikan guru dapat membuka file tanpa meminta izin akses.</small></div>${s?.feedback?`<div class="notice"><b>Catatan guru:</b> ${esc(s.feedback)}</div>`:''}${st==='graded'?`<div class="card"><b>Nilai: ${esc(s.score??'-')}</b><div class="meta">Kategori: <b>${esc(scoreCategory(s.score)||'-')}</b></div></div>`:st==='submitted'?`<div class="notice"><b>Sudah dikumpulkan${g?' oleh '+esc(s.submittedByName||'anggota kelompok'):''}.</b><br><small>${esc(s.submittedAt||'')}</small></div>`:`<div class="actions"><button id="draft" class="secondary">Simpan Draf</button><button id="submit" class="primary">${st==='revision'?'Kumpulkan Ulang':'Kumpulkan'}</button></div>`}`);if(!locked){$('#draft').onclick=()=>save(t,s,g,'draft');$('#submit').onclick=()=>save(t,s,g,'submitted')}}
async function save(t,s,g,status){const components=taskComponents(t),answers=[];for(let ci=0;ci<components.length;ci++){const c=components[ci];for(let ii=0;ii<Math.max(1,Number(c.count)||1);ii++){const key=answerKey(ci,ii),el=document.querySelector(`[data-answer="${key}"]`),v=(el?.value||'').trim(),desc=(document.querySelector(`[data-description="${key}"]`)?.value||'').trim(),label=`${c.label||'Jawaban'}${Number(c.count)>1?' '+(ii+1):''}`;if(status==='submitted'&&c.required&&!v)return alert(`${label} wajib diisi.`);if(status==='submitted'&&v&&c.requireDescription&&c.type!=='text'&&!desc)return alert(`Keterangan untuk ${label} wajib diisi.`);if(c.type!=='text'&&v){try{const u=new URL(v);if(!['http:','https:'].includes(u.protocol))throw new Error()}catch(_){return alert(`Link ${label} belum valid. Awali dengan https://`)}}answers.push({componentIndex:ci,itemIndex:ii,type:c.type,label,url:c.type==='text'?'':v,text:c.type==='text'?v:'',description:c.type==='text'?'':desc})}}const now=new Date().toISOString(),isGroup=t.taskType==='group',docId=isGroup?g.groupKey:`${t.id}_${profile.loginId}`,ref=s?db.collection('taskSubmissions').doc(s.id):db.collection('taskSubmissions').doc(docId);const data={taskId:t.id,taskType:isGroup?'group':'individual',studentUid:user.uid,studentId:profile.studentId||'',nis:s?.nis||String(profile.loginId),studentName:s?.studentName||profile.name||'',classId:norm(profile.classId),groupNo:isGroup?g.groupNo:null,groupKey:isGroup?g.groupKey:'',memberNis:isGroup?(g.memberNis||[]):[],memberNames:isGroup?(g.memberNames||[]):[],answers,reflection:'',status,submittedAt:status==='submitted'?now:(s?.submittedAt||null),submittedByNis:status==='submitted'?String(profile.loginId):(s?.submittedByNis||''),submittedByName:status==='submitted'?(profile.name||''):(s?.submittedByName||''),updatedAt:now,updatedByNis:String(profile.loginId)};try{await ref.set(data,{merge:true});close();await load();alert(status==='draft'?'Draf berhasil disimpan.':isGroup?'Tugas kelompok berhasil dikumpulkan untuk seluruh anggota.':'Tugas berhasil dikumpulkan.')}catch(e){alert('Gagal menyimpan: '+e.message)}}
function showError(msg,hint=''){ $('#loading').classList.add('hidden');$('#app').classList.add('hidden');$('#error').classList.remove('hidden');$('#error').innerHTML=`<h2>Tugas belum dapat dibuka</h2><p>${esc(msg)}</p>${hint?`<div class="notice">${esc(hint)}</div>`:''}<p><a href="../">Kembali ke Beranda</a></p>`}
auth.onAuthStateChanged(async u=>{if(!u)return showError('Sesi siswa tidak ditemukan.','Silakan login dari halaman siswa.');user=u;try{const d=await db.collection('users').doc(u.uid).get();if(!d.exists)throw new Error('Profil sesi siswa tidak ditemukan.');profile=d.data();if(profile.role!=='siswa'||profile.active!==true)throw new Error('Halaman ini khusus siswa aktif.');profile.classId=norm(profile.classId);$('#loading').classList.add('hidden');$('#app').classList.remove('hidden');$('#profileLabel').textContent=`${profile.name||'Siswa'} • Kelas ${profile.classId}`;$('#diagnostic').textContent=`NIS ${profile.loginId} • Kelas ${profile.classId}`;await load()}catch(e){showError(e.message,e.code==='permission-denied'?'Firestore Rules perlu diperbarui untuk tugas kelompok/rentang nilai.':'Pastikan tugas sudah diterbitkan dan kelas siswa termasuk kelas sasaran.')}});
